#Do not delete this file
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=673540872688.dkr.ecr.eu-west-1.amazonaws.com/arrium-backend-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker login -u nirajvisana -p 975c5aef-1325-4316-91be-f86329560346
      - docker build -f docker-compose.prod.yml -t $REPOSITORY_URI:latest .
#      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
      - docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 673540872688.dkr.ecr.eu-west-1.amazonaws.com/arrium-backend-app:latest
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - printf '[{"name":"nginx_arrium","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
